#!/usr/bin/env bash
#NETSMILE_CONFIGURATION_SERVICE=https://configuration-service.aiscanrobo.dev.netsmile.jp

echo "Updating .env.local with config from $NETSMILE_CONFIGURATION_SERVICE"

AUTH0_CLIENT_SECRET=$(netsmile-configuration --quiet-read aiscanrobo-general --key auth0Secret)
AUTH0_SECRET=$(netsmile-configuration --quiet-read aiscanrobo-general --key auth0LocalUISecret)
AUTH0_CLIENT_ID=$(netsmile-configuration --quiet-read aiscanrobo-general --key auth0ClientId)
AUTH0_ISSUER_BASE_URL="https://"$(netsmile-configuration --quiet-read aiscanrobo-general --key auth0Domain)
AUTH0_BASE_URL="http://localhost:3995"
INTERNAL_API_SECRET=$(netsmile-configuration --quiet-read aiscanrobo-general --key internalApiSecret)
USER_SERVICE_API_URL=$(netsmile-configuration --quiet-read aiscanrobo-general --key userServiceApiExternalUrl)
TEMPLATELESS_API_V2_URL=$(netsmile-configuration --quiet-read templateless-general --key templatelessApiExternalUrlV2)
NEXT_PUBLIC_MUI_X_LICENSE_KEY=$(netsmile-configuration --quiet-read asralpha-ui --key muiXLicenseKey)

echo "AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET"
echo "AUTH0_SECRET=$AUTH0_SECRET"
echo "AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID"
echo "AUTH0_ISSUER_BASE_URL=$AUTH0_ISSUER_BASE_URL"
echo "AUTH0_BASE_URL=$AUTH0_BASE_URL"
echo "INTERNAL_API_SECRET=$INTERNAL_API_SECRET"
echo "USER_SERVICE_API_URL=$USER_SERVICE_API_URL"
echo "TEMPLATELESS_API_V2_URL=$TEMPLATELESS_API_V2_URL"
echo "NEXT_PUBLIC_MUI_X_LICENSE_KEY=$NEXT_PUBLIC_MUI_X_LICENSE_KEY"

# If the file .env.local exists, make a backup of it first
if [ -f .env.local ]; then
  cp .env.local .env.local.backup-$(date +%Y%m%d%H%M%S)
fi

echo "# Generated by get-config.sh" > .env.local
echo "# For running against $NETSMILE_CONFIGURATION_SERVICE" >> .env.local
echo "NEXT_PUBLIC_MUI_X_LICENSE_KEY=\"$NEXT_PUBLIC_MUI_X_LICENSE_KEY\"" >> .env.local
echo "AUTH0_CLIENT_SECRET=\"$AUTH0_CLIENT_SECRET\"" >> .env.local
echo "AUTH0_SECRET=\"$AUTH0_SECRET\"" >> .env.local
echo "AUTH0_CLIENT_ID=\"$AUTH0_CLIENT_ID\"" >> .env.local
echo "AUTH0_ISSUER_BASE_URL=\"$AUTH0_ISSUER_BASE_URL\"" >> .env.local
echo "AUTH0_BASE_URL=\"$AUTH0_BASE_URL\"" >> .env.local
echo "INTERNAL_API_SECRET=\"$INTERNAL_API_SECRET\"" >> .env.local
echo "# For running against remote user-service-api" >> .env.local
echo "USER_SERVICE_API_URL=\"$USER_SERVICE_API_URL\"" >> .env.local
echo "# For running against local user-service-api" >> .env.local
echo '#USER_SERVICE_API_URL="http://localhost:7775"' >> .env.local
echo "# For running against remote templateless-api-v2" >> .env.local
echo "TEMPLATELESS_API_V2_URL=\"$TEMPLATELESS_API_V2_URL\"" >> .env.local
echo "# For running against local templateless-service-api-v2" >> .env.local
echo '#TEMPLATELESS_API_V2_URL="http://localhost:8446"' >> .env.local
